imprv: update eslint parser to @babel/eslint-parser
weseek/eslint-config-weseek pull request #5
Opened 2022-03-10 07:07 UTC by yuto-oweseek

## タスク

https://redmine.weseek.co.jp/issues/89780

## 行ったこと

- eslint の parser を更新
- context: https://github.com/weseek/growi-unique-ogp/pull/11#discussion_r788534627

## 簡単な動作確認

- OGP リポジトリ (https://github.com/weseek/growi-unique-ogp ) の node_modules > eslint-config-weseekを現在の PR の状態のコードに書き換えて動作確認しました

2022-03-10 10:05 UTC, yuki-takei requested changes

2022-03-10 10:05 UTC, yuki-takei commented on package.json
> +    "@babel/eslint-parser": "^7.17.0",
peerDependencies しかいじってないのに yarn.lock にこんなに差分有るのおかしいのでは？

2022-03-14 04:11 UTC, yuto-oweseek commented on package.json
> +    "@babel/eslint-parser": "^7.17.0",
別ブランチでも多く差分がでる件について確認してみました。

- @babel/core 自体に Dependencies が多く yarn.lock で多く差分が出現するようです
- @babel/eslint-parser の npm サイト https://www.npmjs.com/package/babel-eslint-parser を見てみると、`Installation` の箇所に、 @babel/core があるので、あったほうがいいと思われます

2022-03-24 07:05 UTC, yuto-oweseek commented on package.json
> +    "@babel/eslint-parser": "^7.17.0",
- FB 対応

↓ `peerDependencies` について調べた調査結果です。

https://dev.growi.org/%E9%96%8B%E7%99%BA%E6%97%A5%E8%A8%98/peerDependencies

- おそらく  `yarn add <package> -P --frozen-lockfile` でライブラリを追加していたため、過去に追加されていたライブラリが yarn.lock に依存関係の記載がなかったみたいです
- なので、同様に合わせました

2022-03-24 08:36 UTC, yuki-takei approved these changes

2022-03-24 08:37 UTC, merged